artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1iPSSu3l8bYz36l9oEic3RhgW-EgF_oN9/view?usp=sharing
  local_dir: artifacts/data_ingestion/loan_default.csv
  data_dir: artifacts/data_ingestion/data
data_transformation:
  root_dir: artifacts/data_transformation
  split_dir: artifacts/data_transformation/split_data
  preprocess_obj: artifacts/data_transformation/preprocess_obj
model_training:
  root_dir: artifacts/model_training
  best_model: artifacts/model_training/best_model.pkl