artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1iPSSu3l8bYz36l9oEic3RhgW-EgF_oN9/view?usp=sharing
  local_dir: artifacts/data_ingestion/loan_default.csv
  split_dir: artifacts/data_ingestion/split_data